01-FrontEnd/ViewModels/ContactViewModel.cs
using Model.Custom;
using Model.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.ViewModels
{
    public class CreateContactPerAccount
    {
        public ContactCard ContactCard { get; set; }
        public IEnumerable<Account> Accounts { get; set; }
    }
}

01-FrontEnd/Controllers/AccountsController.cs
using Common;
using Service;
using Model.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FrontEnd.App_Start;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private IAccountsService _accountsService = DependecyFactory.GetInstance<IAccountsService>();
        // GET: Accounts
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List(int id = 0, int id_vista = 0)
        {
            ViewBag.Message = "Your application description page.";
            ViewBag.IdList = id;
            ViewBag.Controlador = id_vista;
            return View(_accountsService.Detail(id));
        }

        [HttpPost]
        public JsonResult GetAccounts(AnexGRID grid, int id)
        {
            return Json(
                _accountsService.GetAll(grid, id)
            );
        }

        // GET: Accounts/Details/5
        public ActionResult Details(int id, int id_vista = 0)
        {
            ViewBag.Controlador = 1;
            return View(
                _accountsService.Detail(id)
            );
        }

        // GET: Accounts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Accounts/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Accounts/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Accounts/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Accounts/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

01-FrontEnd/Controllers/ContactController.cs
using Common;
using Service;
using Model.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FrontEnd.App_Start;
using Model.Custom;
using FrontEnd.ViewModels;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private IContactService _contactService = DependecyFactory.GetInstance<IContactService>();
        private IAccountsService _accountService = DependecyFactory.GetInstance<IAccountsService>();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int id = 0, int id_vista = 0)
        {
            ViewBag.Message = "Your application description page.";
            ViewBag.IdList = id;
            ViewBag.Controlador = id_vista;

            var model = new CreateContactPerAccount();
            model.Accounts = _accountService.GetAll();
            model.ContactCard = new ContactCard();
            return View(model);
        }

        //public ActionResult ListAccounts(int id = 0)
        //{
        //    ViewBag.Message = "Your application description page.";
        //    ViewBag.IdList = id;

        //    return View(_contactService.Detail(id));
        //}

        [HttpPost]
        public JsonResult GetContact(int id)
        {
            return Json(
                _contactService.Get(id)
            );
        }

        [HttpPost]
        public JsonResult GetContacts(AnexGRID grid)
        {
            return Json(
                _contactService.GetAll(grid)
            );
        }
        [HttpPost]
        public JsonResult ContactSave (ContactCard model)
        {
            var rh = new ResponseHelper();

            if (!ModelState.IsValid)
            {
                var validations = ModelState.GetErrors();
                rh.SetValidations(validations);
            }
            else
            {
                rh = _contactService.InsertOrUpdate(model);
                if (rh.Response)
                {
                    rh.Href = "self";
                }
            }

            return Json(rh);
        }

        [HttpPost]
        public JsonResult DeleteContact(int id)
        {
            return Json(
                _contactService.Delete(id)
            );
        }

        public ActionResult Details(int id)
        {
            ViewBag.Controlador = 1;
            return View(
                _contactService.Detail(id)
            );
        }
    }
}

01-FrontEnd/Controllers/LeadController.cs
using Common;
using Model.Domain;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class LeadController : Controller
    {
        private ILeadService _leadService = DependecyFactory.GetInstance<ILeadService>();
        // GET: Lead
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SaveLead(Lead model)
        {
            return Json(
                _leadService.InsertOrUpdate(model));
        }

        // GET: Lead/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Lead/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Lead/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Lead/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Lead/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Lead/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Lead/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

01-FrontEnd/Controllers/OpportunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class OpportunityController : Controller
    {
        // GET: Opportunity
        public ActionResult Index()
        {
            return View();
        }

        // GET: Opportunity/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Opportunity/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Opportunity/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Opportunity/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Opportunity/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Opportunity/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Opportunity/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

01-FrontEnd/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class TaskController : Controller
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        // GET: Task/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Task/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Task/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

01-FrontEnd/Views/Contact/Partials/_List.cshtml
<div id="list"></div>

<!-- Modal -->
<div class="modal fade" id="contact-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("ContactSave", "Contact", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Contacto</h4>
                </div>
                <div class="modal-body">
                    <contacts url="@Url.Action("GetContact", "Contact")"></contacts>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit"
                            data-reset="true"
                            data-ajax="true"
                            class="btn btn-primary">
                        Guardar
                    </button>
                </div>
            }
        </div>
    </div>
</div>

01-FrontEnd/Views/Contact/Partials/_Menu.cshtml
<div class="btn-group btn-group-justified" role="group">
    @if (ViewBag.Controlador == 1)
    {
        <div class="btn-group" role="group">
            <a href="@Url.Action("Details", "Contact", new { id = Model.ContactId, id_vista = 1 })" class="btn btn-success">
                <i class="fa fa-list-alt"></i> Resumen
            </a>
        </div>
    }
    else
    {
        <div class="btn-group" role="group">
            <a href="@Url.Action("Details", "Contact", new { id = Model.ContactId, id_vista = 1 })" class="btn btn-default">
                <i class="fa fa-list-alt"></i> Resumen
            </a>
        </div>
    }

    <div class="btn-group" role="group">
        <a href="@Url.Action("DetailEdit", "Contact", new { id = Model.ContactId })" class="btn btn-default">
            <i class="fa fa-address-book-o"></i> Perfil
        </a>
    </div>

    @if (ViewBag.Controlador == 2)
    {
        <div class="btn-group" role="group">
            <a href="@Url.Action("List", "Accounts", new { id = Model.AccountId, id_vista = 1 })" class="btn btn-success">
                <i class="fa fa-building-o"></i> Cuenta
            </a>
        </div>
    }
    else
    {
        <div class="btn-group" role="group">
            <a href="@Url.Action("List", "Accounts", new { id = Model.AccountId, id_vista = 1 })" class="btn btn-default">
                <i class="fa fa-building-o"></i> Cuenta
            </a>
        </div>
    }

    <div class="btn-group" role="group">
        <a href="@Url.Action("DetailEdit", "Lead")" class="btn btn-default">
            <i class="fa fa-search"></i> Lead
        </a>
    </div>
    <div class="btn-group" role="group">
        <a href="@Url.Action("DetailEdit", "Opportunity")" class="btn btn-default">
            <i class="fa fa-diamond"></i> Oportunidades
        </a>
    </div>
    <div class="btn-group" role="group">
        <a href="@Url.Action("DetailEdit", "Task")" class="btn btn-default">
            <i class="fa fa-tasks"></i> Tareas
        </a>
    </div>
</div>

<br />