01-FrontEnd/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.ViewModels
{
    public class UserBasicInformationViewModel
    {
        [Required]
        public string Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string FatherLastName { get; set; }
        [Required]
        public string MotherLastName { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
    }
}

01-FrontEnd/Controllers/PanelController.cs
using Service;
using Common;
using System.Web.Mvc;
using Model.Domain;
using FrontEnd.App_Start;
using Model.Custom;

namespace FrontEnd.Controllers
{
    public class PanelController : Controller
    {
        private IUserService _userService = DependecyFactory.GetInstance<IUserService>();
        private IContactService _contactService = DependecyFactory.GetInstance<IContactService>();
        // GET: Course
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Categories()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Category(int id = 0)
        {
            return Json(null);
        }

        public ActionResult Courses()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetUsers(AnexGRID grid)
        {
            return Json(
                _userService.GetAll(grid)
            );
        }

        [HttpPost]
        public JsonResult ContactSave(ContactCard model)
        {
            var rh = new ResponseHelper();

            if (!ModelState.IsValid)
            {
                var validations = ModelState.GetErrors();
                rh.SetValidations(validations);
            }
            else
            {
                rh = _contactService.InsertOrUpdate(model);
                if (rh.Response)
                {
                    rh.Href = "self";
                }
            }

            return Json(rh);
        }
    }
}

01-FrontEnd/Views/Panel/Categories.cshtml
@{
    ViewBag.Title = "Categorías";
}
<h1 class="page-header">
    <button type="button" class="btn btn-default pull-right btn-sm" data-toggle="modal" data-target="#category-edit">
        <i data-toggle="tooltip" data-placement="top" title="Nueva categoría" class="fa fa-plus"></i>
    </button>
    @ViewBag.Title
</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Categories)

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th style="width:40px;">Ícono</th>
            <th>Nombre</th>
            <th class="text-right" style="width:100px;">Cursos</th>
            <th class="text-right" style="width:100px;">Alumnos</th>
            <th style="width:100px;"></th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 1; i < 20; i++)
        {
            <tr>
                <td>
                    <span class="badge">
                        <i class="fa fa-code"></i>
                    </span>
                </td>
                <td>Curso @i</td>
                <td class="text-right">@(i * 2)</td>
                <td class="text-right">@(i * 10)</td>
                <td class="text-center">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-sm">
                            <i title="Eliminar" data-toggle="tooltip" data-placement="top" class="fa fa-trash"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#category-edit">
                            <i title="Editar" data-toggle="tooltip" data-placement="top" class="fa fa-edit"></i>
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="category-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("ContactSave", "Panel", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Contacto</h4>
                </div>
                <div class="modal-body">
                    <contacts></contacts>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" data-ajax="true" class="btn btn-primary">Guardar</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Assets/vue_components/dist/contacts.components.js"></script>
    }

01-FrontEnd/Views/Panel/Courses.cshtml
@{
    ViewBag.Title = "Cursos";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Courses)

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Nombre</th>
            <th style="width:200px;">Profesor</th>
            <th class="text-right" style="width:100px;">Alumnos</th>
            <th class="text-right" style="width:100px;">Lecciones</th>
            <th style="width:150px;">Estado</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 1; i < 20; i++)
        {
            <tr>
                <td>Curso @i</td>
                <td>Profesor @i</td>
                <td class="text-right">@(i * 2)</td>
                <td class="text-right">@(i * 10)</td>
                <td>
                    <select class="form-control input-sm">
                        <option class="1">Pendiente</option>
                        <option class="1">Rechazado</option>
                        <option class="1">Aprobado</option>
                    </select>
                </td>
            </tr>
        }
    </tbody>
</table>

01-FrontEnd/Views/Panel/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Home)

<h2 class="page-header">Ingresos</h2>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Ingreso Total
                <span class="badge pull-right">
                    <i class="fa fa-line-chart"></i>
                </span>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    Ingreso Total (100 %)<span class="badge">$ 12,500.25</span>
                </li>
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName (@(Parameters.SalesCommission)%) <span class="badge">$ 5,250.12</span>
                </li>
                <li class="list-group-item">
                    Pago a profesores (@(100 - Parameters.SalesCommission)%) <span class="badge">$ 7,250.12</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Ingreso del mes actual
                <span class="badge pull-right">
                    <i class="fa fa-calendar"></i>
                </span>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    Ingreso Total (100 %)<span class="badge">$ 2,500.25</span>
                </li>
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName (@(Parameters.SalesCommission)%) <span class="badge">$ 750.12</span>
                </li>
                <li class="list-group-item">
                    Pago a profesores (@(100 - Parameters.SalesCommission)%) <span class="badge">$ 1,750.12</span>
                </li>
            </ul>
        </div>
    </div>
</div>

<h2 class="page-header">Estadística</h2>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Variación Porcentual (Mes actual)
                <span class="badge pull-right">
                    <i class="fa fa-line-chart"></i>
                </span>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Alumnos <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Profesores <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Cursos creados <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Media aritmética (Por mes)
                <span class="badge pull-right">
                    <i class="fa fa-bar-chart"></i>
                </span>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName <span class="badge">$ 100,200.00</span>
                </li>
                <li class="list-group-item">
                    Alumnos <span class="badge">100</span>
                </li>
                <li class="list-group-item">
                    Profesores <span class="badge">7</span>
                </li>
                <li class="list-group-item">
                    Cursos creados <span class="badge">7</span>
                </li>
            </ul>
        </div>
    </div>
</div>

01-FrontEnd/Views/Panel/Users.cshtml
@{
    ViewBag.Title = "Usuarios";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Users)

@*<table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th style="width:200px;">Correo</th>
                <th style="width:300px;">Roles</th>
                <th class="text-right" style="width:150px;">Oportunidades</th>
                <th class="text-right" style="width:150px;">Cursos creados</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 1; i < 20; i++)
            {
                <tr>
                    <td>Usuario @i</td>
                    <td>@i-user@anexu.com</td>
                    <td>User, Teacher, Student</td>
                    <td class="text-right">@(i * 3)</td>
                    <td class="text-right">@(i * 2)</td>
                </tr>
            }
        </tbody>
    </table>*@

<div id="list"></div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var conf = {
                class: 'table-striped table-bordered',
                columnas: [
                    { leyenda: 'Nombre', columna: 'FullName' },
                    { leyenda: 'Correo', style: 'width:150;', columna: 'Email' },
                    { leyenda: 'Roles', style: 'width:150;' },
                    { leyenda: 'Oportunidades Cerradas', style: 'width:150px;', columna: 'OpportunitiesClosed' },
                ],
                modelo: [
                    { propiedad: 'FullName' },
                    { propiedad: 'Email' },
                    {
                        propiedad: 'Roles', formato: function (tr, obj, value) {
                             return value.join(', ');
                        }
                    },
                    { propiedad: 'OpportunitiesClosed' },
                ],
                url: '@Url.Action("GetUsers", "Panel")',
                limite: 20,
                paginable: true,
                columna: 'FullName',
                columna_orden: 'ASC'
            };

            $("#list").anexGrid(conf);
        })
    </script>
}